"""The documentation site's own invariants.

Documentation fails quietly. A page that stops being listed, a link that points
at a file somebody renamed, an agent index that silently drops half the corpus
- none of it raises, and none of it is noticed by the person who caused it.

`mkdocs build --strict` in CI covers broken internal links. These cover the
things it does not: that the agent-readable index still describes every page,
and that generated files are still generated rather than hand-edited.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[1]
MKDOCS = ROOT / "mkdocs.yml"


def _config() -> dict[str, Any]:
    """mkdocs.yml, parsed.

    `yaml.safe_load` is enough here: the file uses no custom tags, and adding
    one would break this loudly rather than silently.
    """
    yaml = pytest.importorskip("yaml", reason="pyyaml arrives with the docs group")
    loaded: dict[str, Any] = yaml.safe_load(MKDOCS.read_text(encoding="utf-8"))
    return loaded


def _nav_pages(node: Any, found: set[str] | None = None) -> set[str]:
    """Every markdown file the nav points at, at any nesting depth."""
    found = set() if found is None else found
    if isinstance(node, dict):
        for value in node.values():
            _nav_pages(value, found)
    elif isinstance(node, list):
        for value in node:
            _nav_pages(value, found)
    elif isinstance(node, str) and node.endswith(".md"):
        found.add(node)
    return found


def _llms_sections(config: dict[str, Any]) -> dict[str, list[Any]]:
    for plugin in config.get("plugins", []):
        if isinstance(plugin, dict) and "llmstxt" in plugin:
            sections: dict[str, list[Any]] = plugin["llmstxt"].get("sections", {})
            return sections
    return {}


def _llms_pages(config: dict[str, Any]) -> set[str]:
    """Every page named in the llmstxt sections.

    Entries are either a bare path or a single-key mapping of path to
    description, so both shapes have to be handled.
    """
    pages: set[str] = set()
    for entries in _llms_sections(config).values():
        for entry in entries:
            pages.add(next(iter(entry)) if isinstance(entry, dict) else entry)
    return pages


def test_the_agent_index_describes_every_page() -> None:
    """A page missing from llms.txt is invisible to anything reading it.

    Nothing else catches this: the site builds, the page is reachable, and the
    index simply does not mention it. The failure mode is an agent confidently
    telling someone a feature is undocumented.
    """
    config = _config()
    nav = _nav_pages(config.get("nav", []))
    listed = _llms_pages(config)

    missing = nav - listed
    assert not missing, f"nav pages absent from the llmstxt sections: {sorted(missing)}"


def test_the_agent_index_does_not_describe_pages_that_are_gone() -> None:
    """The other direction. A stale entry points an agent at a 404, which is
    worse than an omission because it looks like the page should exist.
    """
    config = _config()
    listed = _llms_pages(config)

    absent = {page for page in listed if not (ROOT / "docs" / page).exists()}
    assert not absent, f"llmstxt lists files that do not exist: {sorted(absent)}"


def test_every_listed_page_carries_a_description() -> None:
    """The whole value of the index is letting something decide *not* to open a
    page. A bare path gives it nothing to decide on.
    """
    config = _config()

    bare = [
        entry
        for entries in _llms_sections(config).values()
        for entry in entries
        if not isinstance(entry, dict)
    ]
    assert not bare, f"listed without a description: {bare}"


# ------------------------------------------------------------- generated ---


def test_the_api_reference_is_not_hand_edited() -> None:
    """It carries a header saying so, and CI regenerates it to check.

    This asserts the warning is still there: someone who removes it is the
    someone about to edit the file by hand.
    """
    api = (ROOT / "docs" / "reference" / "api.md").read_text(encoding="utf-8")

    assert "Generated by scripts/export_openapi.py" in api
    assert "Do not edit" in api


def test_the_api_reference_links_resolve_to_its_own_headings() -> None:
    """The endpoint index links to anchors on the same page.

    Markdown removes a slash rather than turning it into a hyphen, so these are
    easy to get wrong by hand - and they were, before the generator computed
    them. `mkdocs --strict` catches it too, but only when the docs group is
    installed, and this runs anywhere.
    """
    api = (ROOT / "docs" / "reference" / "api.md").read_text(encoding="utf-8")

    headings = {
        re.sub(r"[-\s]+", "-", re.sub(r"[^\w\s-]", "", line[3:]).strip().lower())
        for line in api.splitlines()
        if line.startswith("## ")
    }
    links = set(re.findall(r"\]\(#([a-z0-9_-]+)\)", api))

    assert links, "the endpoint index has no anchor links at all"
    assert links <= headings, f"links with no matching heading: {sorted(links - headings)}"
