"""Domain logic.

Keeps business rules out of route handlers, so they can be tested without HTTP
and reused from a CLI later (§32.12). Phase 6's send logic belongs here too.
"""

from seskit_core.services.api_keys import (
    IssuedKey,
    create_api_key,
    get_owned_api_key,
    list_api_keys,
    revoke_api_key,
    touch_last_used,
    verify_api_key,
)
from seskit_core.services.aws import (
    ProviderFactory,
    check_is_allowed,
    clear_check_marker,
    connect_aws,
    disconnect_aws,
    get_connection,
    refresh_connection,
)
from seskit_core.services.events import (
    ProvisionerFactory,
    count_other_users,
    queue_name_for,
    set_open_click_tracking,
    setup_events,
    teardown_events,
    topic_name_for,
)
from seskit_core.services.identities import (
    add_identity,
    check_identity,
    classify,
    count_other_references,
    find_identity,
    get_owned_identity,
    identities_due,
    is_recheck_due,
    list_identities,
    refresh_identity,
    remove_identity,
)
from seskit_core.services.projects import (
    create_project,
    get_default_project,
    get_owned_project,
    list_projects,
)
from seskit_core.services.sending import (
    attachment_rows,
    choose_provider,
    configuration_set_for,
    find_by_idempotency_key,
    is_retryable,
    record_failure,
    record_sent,
    sender_is_verified,
    to_outbound,
)
from seskit_core.services.users import (
    EmailAlreadyRegistered,
    SignupClosed,
    authenticate,
    count_users,
    get_user_by_email,
    get_user_by_id,
    register_user,
    signup_allowed,
)

__all__ = [
    "EmailAlreadyRegistered",
    "IssuedKey",
    "ProviderFactory",
    "ProvisionerFactory",
    "SignupClosed",
    "add_identity",
    "attachment_rows",
    "authenticate",
    "check_identity",
    "check_is_allowed",
    "choose_provider",
    "classify",
    "clear_check_marker",
    "configuration_set_for",
    "connect_aws",
    "count_other_references",
    "count_other_users",
    "count_users",
    "create_api_key",
    "create_project",
    "disconnect_aws",
    "find_by_idempotency_key",
    "find_identity",
    "get_connection",
    "get_default_project",
    "get_owned_api_key",
    "get_owned_identity",
    "get_owned_project",
    "get_user_by_email",
    "get_user_by_id",
    "identities_due",
    "is_recheck_due",
    "is_retryable",
    "list_api_keys",
    "list_identities",
    "list_projects",
    "queue_name_for",
    "record_failure",
    "record_sent",
    "refresh_connection",
    "refresh_identity",
    "register_user",
    "remove_identity",
    "revoke_api_key",
    "sender_is_verified",
    "set_open_click_tracking",
    "setup_events",
    "signup_allowed",
    "teardown_events",
    "to_outbound",
    "topic_name_for",
    "touch_last_used",
    "verify_api_key",
]
