#!/usr/bin/env python3
"""Render the API reference from the OpenAPI schema.

The schema is already the source of truth: FastAPI derives it from the same
Pydantic models the routes validate against. A hand-maintained endpoint table
is a second source of truth that drifts from the first within a couple of
commits, and the drift is invisible until a reader follows it.

So the reference is generated, and CI checks the committed copy still matches
what the code produces:

    uv run python scripts/export_openapi.py           # regenerate
    uv run python scripts/export_openapi.py --check   # fail if stale

The output is committed rather than built during ``mkdocs build``, for two
reasons. The docs site builds on a runner that has no database and no
application environment, and a generated file in git is a file whose changes
show up in review - an endpoint that quietly changed shape is then a diff
someone reads, rather than a silent difference between two deploys.

Stdlib only apart from the app itself. This runs in the same environment as the
test suite and needs nothing the project does not already install.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import unicodedata
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "docs" / "reference" / "openapi.json"
MARKDOWN_PATH = ROOT / "docs" / "reference" / "api.md"

#: Fixed so the output depends on the code and nothing else. Whatever is in the
#: developer's environment must not change what lands in git - a reference that
#: differs between two machines is worse than no reference.
STUB_ENVIRONMENT = {
    "SECRET_KEY": "generate-openapi",
    "DATABASE_URL": "postgresql+asyncpg://seskit:seskit@localhost:55432/seskit",
    "REDIS_URL": "redis://localhost:56379/0",
    "ENVIRONMENT": "local",
}

#: Endpoints the reference is about. /healthz and /readyz are in the schema and
#: belong in the operating documentation, not here.
PUBLIC_PREFIX = "/v1"

HEADER = """<!--
  Generated by scripts/export_openapi.py from the OpenAPI schema. Do not edit
  by hand: the next regeneration will overwrite it, and CI fails if this file
  and the code disagree.

      uv run python scripts/export_openapi.py
-->

# HTTP API

Every endpoint below is derived from the running application's OpenAPI schema,
so it cannot describe an endpoint that does not exist or miss a field that
does. The raw schema is [openapi.json](openapi.json); a running instance also
serves it at `/openapi.json`, with interactive documentation at `/docs`.

## Authentication

Every `/v1` endpoint takes an API key as a bearer token:

```bash
curl https://your-seskit-instance/v1/emails/email_01J8XQ... \\
  -H "Authorization: Bearer sk_..."
```

Keys are scoped to a project and created in the dashboard. A missing header and
an invalid token both return `401` with the same message — distinguishing them
would tell whoever is probing which half they had right.

## Errors

One shape, always:

```json
{ "error": { "type": "domain_not_verified", "message": "..." } }
```

Branch on `type`, which is stable; show `message` to humans. The full list is
in [Errors](errors.md).

## Rate limits

Per project, not per key. Every response carries `X-RateLimit-Limit`,
`X-RateLimit-Remaining` and `X-RateLimit-Reset`; exceeding the limit returns
`429`.

!!! note "One endpoint is deliberately absent"
    `POST /v1/events/ses` receives SES notifications from Amazon SNS and is
    excluded from the schema, because it is not for callers — it authenticates
    by verifying SNS's signature rather than by API key, and is only mounted
    when `EVENT_INGESTION` asks for it. See
    [delivery events](../guides/delivery-events.md).
"""


def build_schema() -> dict[str, Any]:
    """The schema the application itself would serve."""
    for key, value in STUB_ENVIRONMENT.items():
        os.environ.setdefault(key, value)

    # Imported here, after the environment is set: settings are read at import
    # time by some modules.
    from seskit_api.main import create_app

    schema: dict[str, Any] = create_app().openapi()
    return schema


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _slug(text: str) -> str:
    """The anchor Python-Markdown will give a heading with this text.

    Reimplemented rather than imported, because ``markdown`` belongs to the
    docs dependency group and this script runs in the main environment.

    Guessing the rule is what makes hand-written anchors rot: a slash is
    *removed*, not turned into a hyphen, so ``GET /v1/api-keys`` becomes
    ``get-v1api-keys`` and not ``get-v1-api-keys``. mkdocs --strict catches a
    wrong one, which is the backstop for this ever drifting.
    """
    value = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")
    value = re.sub(r"[^\w\s-]", "", value).strip().lower()
    return re.sub(r"[-\s]+", "-", value)


def _type_of(schema: dict[str, Any]) -> str:
    """A human-readable type for one property.

    Deliberately shallow. This is a reference table, not a schema browser - a
    reader who needs the exact shape has openapi.json beside it.
    """
    if "$ref" in schema:
        return _ref_name(schema["$ref"])

    # Pydantic renders optionals as anyOf[..., null].
    if "anyOf" in schema:
        parts = [_type_of(s) for s in schema["anyOf"] if s.get("type") != "null"]
        return " or ".join(dict.fromkeys(parts)) or "null"

    kind = schema.get("type", "any")
    if kind == "array":
        return f"{_type_of(schema.get('items', {}))}[]"
    if "enum" in schema:
        return " · ".join(f"`{v}`" for v in schema["enum"])
    return str(kind)


def _referenced(schema: dict[str, Any]) -> set[str]:
    """Every component name a property mentions, however it is nested."""
    found: set[str] = set()
    if "$ref" in schema:
        found.add(_ref_name(schema["$ref"]))
    for key in ("anyOf", "allOf", "oneOf"):
        for sub in schema.get(key, []):
            found |= _referenced(sub)
    if items := schema.get("items"):
        found |= _referenced(items)
    return found


def _fields_table(
    model: dict[str, Any], components: dict[str, Any], seen: set[str] | None = None
) -> list[str]:
    """A table of one model's properties, one level deep.

    Names of nested models are collected into ``seen`` rather than expanded
    inline, so a table stays a table. They are rendered afterwards under
    Models - without that, a field typed ``AttachmentRequest[]`` is a dead end
    for the reader.
    """
    properties = model.get("properties", {})
    if not properties:
        return []

    required = set(model.get("required", []))
    lines = ["| Field | Type | | |", "|---|---|---|---|"]
    for name, spec in properties.items():
        if seen is not None:
            seen |= _referenced(spec)
        if "$ref" in spec:
            spec = {**components.get(_ref_name(spec["$ref"]), {}), **spec}
        mark = "required" if name in required else "optional"
        default = spec.get("default")
        note = spec.get("description", "")
        if default not in (None, ...) and not note:
            note = f"Defaults to `{json.dumps(default)}`"
        lines.append(f"| `{name}` | {_type_of(spec)} | {mark} | {note} |")
    return lines


def _body_model(operation: dict[str, Any], components: dict[str, Any]) -> dict[str, Any] | None:
    content = operation.get("requestBody", {}).get("content", {})
    schema = content.get("application/json", {}).get("schema")
    if not schema:
        return None
    if "$ref" in schema:
        resolved: dict[str, Any] | None = components.get(_ref_name(schema["$ref"]))
        return resolved
    model: dict[str, Any] = schema
    return model


def render(schema: dict[str, Any]) -> str:
    components = schema.get("components", {}).get("schemas", {})
    paths = schema.get("paths", {})

    public = {p: ops for p, ops in sorted(paths.items()) if p.startswith(PUBLIC_PREFIX)}
    nested: set[str] = set()

    lines = [HEADER.rstrip(), "", "## Endpoints", "", "| Method | Path | |", "|---|---|---|"]
    for path, operations in public.items():
        for method, operation in operations.items():
            summary = operation.get("summary", "")
            # The heading rendered below, slugified the same way Markdown will
            # slugify it - so the two cannot disagree.
            anchor = _slug(f"{method.upper()} {path}")
            lines.append(f"| `{method.upper()}` | [`{path}`](#{anchor}) | {summary} |")

    for path, operations in public.items():
        for method, operation in operations.items():
            lines += ["", "---", "", f"## `{method.upper()} {path}`", ""]

            if summary := operation.get("summary"):
                lines += [f"**{summary}**", ""]
            if description := operation.get("description"):
                lines += [description.strip(), ""]

            parameters = operation.get("parameters", [])
            if parameters:
                lines += ["**Parameters**", "", "| Name | In | | |", "|---|---|---|---|"]
                for parameter in parameters:
                    mark = "required" if parameter.get("required") else "optional"
                    lines.append(
                        f"| `{parameter['name']}` | {parameter['in']} | {mark} "
                        f"| {parameter.get('description', '')} |"
                    )
                lines.append("")

            if model := _body_model(operation, components):
                table = _fields_table(model, components, nested)
                if table:
                    lines += ["**Request body**", "", *table, ""]

            responses = operation.get("responses", {})
            if responses:
                lines += ["**Responses**", "", "| Status | |", "|---|---|"]
                for status_code, response in sorted(responses.items()):
                    lines.append(f"| `{status_code}` | {response.get('description', '')} |")
                lines.append("")

    # Models a request body referred to by name. Rendered here rather than
    # inline, so an endpoint's table stays a table - but rendered, because a
    # field typed AttachmentRequest[] and nothing else is a dead end.
    if models := sorted(name for name in nested if name in components):
        lines += ["", "---", "", "## Models", ""]
        for name in models:
            lines += [f"### `{name}`", ""]
            if description := components[name].get("description"):
                lines += [description.strip(), ""]
            lines += [*_fields_table(components[name], components), ""]

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed files are stale, without writing",
    )
    args = parser.parse_args()

    schema = build_schema()
    schema_text = json.dumps(schema, indent=2, sort_keys=True) + "\n"
    markdown = render(schema)

    if args.check:
        stale = [
            path.relative_to(ROOT).as_posix()
            for path, expected in ((SCHEMA_PATH, schema_text), (MARKDOWN_PATH, markdown))
            if not path.exists() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            print("API reference is stale:", ", ".join(stale), file=sys.stderr)
            print("Regenerate with: uv run python scripts/export_openapi.py", file=sys.stderr)
            return 1
        print("API reference is up to date.")
        return 0

    SCHEMA_PATH.write_text(schema_text, encoding="utf-8")
    MARKDOWN_PATH.write_text(markdown, encoding="utf-8")
    print(f"wrote {SCHEMA_PATH.relative_to(ROOT)} and {MARKDOWN_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
